### ISSUE TITLE
It Aint Working for some reason

### ISSUE THREAD

**Issue by oxie** [asheniam/azure-grafana-dashboard-templates#9]
Hey man,

Thanks for this great tool and I appreciate the time you have put investigating and building this.
Seems like a nice feature that should be included in the Azure plugin at the beginning.

Though running it as shown in the instructions, using on Mac with az cli 2 everything working + service principle etc.  and in the end, it couldn't find the resource type in your git repo. 
I tried modifying the parsing but couldn't manage to get it working. Can you please review.

resourcetype=microsoft.storage/storageaccounts # not found

**Comment by asheniam** [comment]
Have you verified that there are storage accounts on your Azure subscription?  Is this behavior only happening for storage accounts?  Or for other Azure resource types as well?

**Comment by oxie** [comment]
No mate, I've used it for virtual machines, and we do have a lot of those working. It just couldn't find the template in your git repo using the git API, I think its something with parsing the paths, because I tried to build the URL string for extracting the template, but it didn't work  either and I remember I had to add /overview/ at the end  to be able to see it. I`ll try rerunning it again today from clean, and gonna copy/paste the output.

**Comment by oxie** [comment]
Am i missing something here man?

I just tested out the functionality again and this is what i get: 

```Valentins-MacBook-Pro:armclient valentinpetrov$ 

armclient --config.file=credentials.yml grafana --title=production --datasource=production-we --resourcetype=microsoft.compute/virtualmachines --debug

DEBU[0000] Getting token from https://login.microsoftonline.com/84e4e65a-c93d-4af1-b169-a65dee46f660/oauth2/token

INFO[0000] Running GET /subscriptions/6f495c4d-b60a-459d-97c9-7fbc408ff8ed/resources?api-version=2017-08-01

DEBU[0000] Executing GET https://management.azure.com/subscriptions/6f495c4d-b60a-459d-97c9-7fbc408ff8ed/resources?api-version=2017-08-01

DEBU[0001] Status code: 200

DEBU[0001] Executing GET https://api.github.com/repos/asheniam/azure-grafana-dashboard-templates/microsoft-compute-virtualmachines?ref=master

DEBU[0002] Status code: 403

No dashboards found for resource type on github

**Comment by oxie** [comment]
When Trying to Execute in browser the Request to the api.github.com i get this responce
```
https://api.github.com/repos/asheniam/azure-grafana-dashboard-templates/microsoft-compute-virtualmachines?ref=master

{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

**Comment by oxie** [comment]
I just forked the repo and rebuild the armclient using my repo, everything works alright now, i guess there are some limits to the Github API

Thanks for your time mate, and sorry for bothering you on this :) 

U da BEst !

**Comment by asheniam** [comment]
Glad to hear it worked.
